-- DEPRECATED — intentionally non-executable compatibility marker.
--
-- Do not run this legacy file. Earlier versions created a public profile
-- trigger that copied role, trust, reputation, verification, and onboarding
-- values from auth.users.raw_user_meta_data. Those fields are not client
-- authority and must never be promoted by a trigger.
--
-- The canonical forward-only schema is maintained in:
--   database/migrations/202608270001_v2_authority_foundation.sql
--   database/migrations/202609150001_auth_profile_session_hardening.sql
-- Apply those migrations through the owner's Supabase migration workflow.
