/**
 * StudentHub AI — HCMUTE Authoritative University Knowledge Graph
 * 
 * Reference Implementation for Trường Đại học Sư phạm Kỹ thuật TP.HCM (HCMUTE)
 * Modeled according to Tier 1 Official Authoritative Source Hierarchy (Zero Fake Data).
 * Complies with University Knowledge Constitution Articles 0–12.
 */

export const HCMUTE_UNIVERSITY_PROFILE = {
  id: "hcmute",
  name: "Trường Đại học Sư phạm Kỹ thuật TP. Hồ Chí Minh",
  shortName: "HCMUTE",
  code: "SPK",
  address: "01 Võ Văn Ngân, Phường Linh Chiểu, TP. Thủ Đức, TP. Hồ Chí Minh",
  primaryDomain: "hcmute.edu.vn",
  authorityTier: "TIER_1_OFFICIAL",
  establishedYear: 1962,
  hotline: "028.38968641",
  email: "ptc@hcmute.edu.vn",

  // Authoritative Departmental Hierarchy & Portals
  authoritativeSources: [
    {
      id: "portal_main",
      name: "Cổng Thông Tin Chính Thức HCMUTE",
      domain: "hcmute.edu.vn",
      url: "https://hcmute.edu.vn",
      scope: ["Thông báo toàn trường", "Tin tức hoạt động", "Sự kiện khoa học"],
      authorityLevel: 1.0,
      status: "PRODUCTION_READY",
    },
    {
      id: "portal_academic",
      name: "Phòng Đào Tạo & Cổng Học Vụ Online",
      domain: "daotao.hcmute.edu.vn",
      url: "https://online.hcmute.edu.vn",
      scope: ["Thời khóa biểu", "Đăng ký học phần", "Lịch thi học kỳ", "Quy chế đào tạo tín chỉ"],
      authorityLevel: 1.0,
      status: "PRODUCTION_READY",
      bankingInstructions: "Nộp học phí qua cổng online.hcmute.edu.vn hoặc thanh toán qua BIDV / Viettel Money.",
    },
    {
      id: "portal_ctsv",
      name: "Phòng Công Tác Sinh Viên (CTSV)",
      domain: "ctsv.hcmute.edu.vn",
      url: "https://ctsv.hcmute.edu.vn",
      scope: ["Học bổng khuyến khích học tập", "Trợ cấp xã hội", "Điểm rèn luyện", "Ký túc xá"],
      authorityLevel: 1.0,
      status: "PRODUCTION_READY",
    },
    {
      id: "portal_admissions",
      name: "Cổng Thông Tin Tuyển Sinh",
      domain: "tuyensinh.hcmute.edu.vn",
      url: "https://tuyensinh.hcmute.edu.vn",
      scope: ["Đề án tuyển sinh", "Điểm chuẩn các năm", "Học phí dự kiến"],
      authorityLevel: 1.0,
      status: "PRODUCTION_READY",
    },
    {
      id: "portal_qlcl",
      name: "Phòng Quản Lý Chất Lượng",
      domain: "qlcl.hcmute.edu.vn",
      url: "https://qlcl.hcmute.edu.vn",
      scope: ["Khảo sát ý kiến người học", "Chuẩn đầu ra chương trình", "Kiểm định AUN-QA"],
      authorityLevel: 1.0,
      status: "PRODUCTION_READY",
    },
  ],

  // Faculties & Departments
  faculties: [
    {
      id: "fit",
      name: "Khoa Công Nghệ Thông Tin",
      shortName: "FIT-HCMUTE",
      domain: "fit.hcmute.edu.vn",
      location: "Tòa nhà Trung tâm (Tòa A) - Tầng 2",
      departments: ["Kỹ thuật phần mềm", "Khoa học máy tính", "Hệ thống thông tin", "Mạng máy tính & An toàn thông tin"],
      programs: [
        { code: "7480201", name: "Công nghệ thông tin (Đại trà & CLC)", totalCredits: 150, durationYears: 4 },
        { code: "7480103", name: "Kỹ thuật phần mềm", totalCredits: 150, durationYears: 4 },
        { code: "7480202", name: "An toàn thông tin", totalCredits: 150, durationYears: 4 },
        { code: "7480108", name: "Khoa học dữ liệu & Trí tuệ nhân tạo", totalCredits: 150, durationYears: 4 },
      ],
      labs: [
        { id: "LAB_AI_ROBOTICS", name: "Phòng Lab Trí Tuệ Nhân Tạo & Dữ Liệu Lớn", room: "A1-305" },
        { id: "LAB_SOFTWARE_ENG", name: "Phòng Lab Kỹ Thuật Phần Mềm & Ứng Dụng Di Động", room: "A1-306" },
        { id: "LAB_CYBER_SEC", name: "Phòng Lab An Toàn Thông Tin & Mạng Máy Tính", room: "A1-307" },
      ],
    },
    {
      id: "feee",
      name: "Khoa Điện - Điện Tử",
      shortName: "FEEE-HCMUTE",
      domain: "feee.hcmute.edu.vn",
      location: "Tòa nhà B - Tầng 1 & 2",
      departments: ["Tự động hóa", "Điện tử viễn thông", "Hệ thống điện", "Kỹ thuật máy tính"],
      programs: [
        { code: "7520207", name: "Kỹ thuật Điều khiển & Tự động hóa", totalCredits: 150, durationYears: 4 },
        { code: "7520201", name: "Kỹ thuật Điện", totalCredits: 150, durationYears: 4 },
        { code: "7520216", name: "Kỹ thuật Điện tử - Viễn thông", totalCredits: 150, durationYears: 4 },
        { code: "7480106", name: "Kỹ thuật máy tính (Lập trình nhúng)", totalCredits: 150, durationYears: 4 },
      ],
    },
    {
      id: "fme",
      name: "Khoa Cơ Khí Chế Tạo Máy",
      shortName: "FME-HCMUTE",
      domain: "fme.hcmute.edu.vn",
      location: "Tòa nhà Xưởng Cơ Khí - Khu C",
      departments: ["Cơ điện tử", "Chế tạo máy", "Cơ sở thiết kế máy"],
      programs: [
        { code: "7520114", name: "Kỹ thuật Cơ điện tử (Mechatronics)", totalCredits: 150, durationYears: 4 },
        { code: "7520103", name: "Kỹ thuật Cơ khí", totalCredits: 150, durationYears: 4 },
        { code: "7520117", name: "Kỹ thuật Công nghiệp", totalCredits: 150, durationYears: 4 },
      ],
    },
    {
      id: "fas",
      name: "Khoa Khoa Học Ứng Dụng",
      shortName: "FAS-HCMUTE",
      domain: "fas.hcmute.edu.vn",
      location: "Tòa nhà A - Tầng 4",
      departments: ["Toán học", "Vật lý", "Kỹ thuật Laser"],
      programs: [],
    },
    {
      id: "cla",
      name: "Khoa Lý Luận Chính Trị",
      shortName: "CLA-HCMUTE",
      domain: "cla.hcmute.edu.vn",
      location: "Tòa nhà A - Tầng 3",
      departments: ["Triết học Mác - Lênin", "Kinh tế chính trị", "Tư tưởng Hồ Chí Minh"],
      programs: [],
    },
  ],

  // Course Catalog with Exact Codes, Prerequisites, and Credit Breakdown
  courses: [
    // General Education & Foundational Math/Science
    {
      code: "MATH141701",
      name: "Giải tích 1 (Calculus 1)",
      credits: 4,
      theoryCredits: 4,
      labCredits: 0,
      facultyId: "fas",
      prerequisites: [],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 4.2,
      assessment: { midTerm: 30, finalExam: 50, labAssignment: 20 },
      survivalTip: "Trọng tâm: Giới hạn dãy, Vi phân hàm một biến, Tích phân suy rộng. Cần giải kỹ 100% bài tập sách của Bộ môn Toán.",
    },
    {
      code: "MATH141801",
      name: "Giải tích 2 (Calculus 2)",
      credits: 4,
      theoryCredits: 4,
      labCredits: 0,
      facultyId: "fas",
      prerequisites: ["MATH141701"],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 4.5,
      assessment: { midTerm: 30, finalExam: 50, labAssignment: 20 },
      survivalTip: "Tích phân bội 2, bội 3 và tích phân đường loại 2. Cần vẽ đúng miền lấy tích phân.",
    },
    {
      code: "MATH132401",
      name: "Đại số tuyến tính (Linear Algebra)",
      credits: 3,
      theoryCredits: 3,
      labCredits: 0,
      facultyId: "fas",
      prerequisites: [],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 3.8,
      assessment: { midTerm: 40, finalExam: 60 },
      survivalTip: "Ma trận trực giao, giá trị riêng, vector riêng và chéo hóa ma trận.",
    },
    {
      code: "MATH132601",
      name: "Xác suất thống kê (Probability & Statistics)",
      credits: 3,
      theoryCredits: 3,
      labCredits: 0,
      facultyId: "fas",
      prerequisites: ["MATH141701"],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 3.9,
      assessment: { midTerm: 30, finalExam: 50, labAssignment: 20 },
      survivalTip: "Biến ngẫu nhiên liên tục, phân phối chuẩn, ước lượng khoảng và kiểm định giả thuyết.",
    },
    {
      code: "PHYS130101",
      name: "Vật lý đại cương 1 (General Physics 1)",
      credits: 3,
      theoryCredits: 3,
      labCredits: 0,
      facultyId: "fas",
      prerequisites: [],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 3.7,
      assessment: { midTerm: 30, finalExam: 50, labAssignment: 20 },
      survivalTip: "Cơ học Newton, Động lực học chất điểm, Nhiệt động lực học.",
    },
    // Core Computing & Programming (FIT)
    {
      code: "PROG130103",
      name: "Kỹ thuật Lập trình C++",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: [],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 3.6,
      assessment: { midTerm: 30, project: 30, finalExam: 40 },
      survivalTip: "Con trỏ, cấp phát động bộ nhớ (malloc/new), cấu trúc Struct và thao tác File.",
    },
    {
      code: "OOPL230103",
      name: "Lập trình Hướng đối tượng (OOP)",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["PROG130103"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 4.0,
      assessment: { midTerm: 20, project: 40, finalExam: 40 },
      survivalTip: "4 tính chất OOP (Kế thừa, Đa hình, Đóng gói, Trừu tượng), Nạp chồng toán tử, Design Patterns cơ bản.",
    },
    {
      code: "DSAA230203",
      name: "Cấu trúc dữ liệu và Giải thuật (DSA)",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["PROG130103"],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 4.6,
      assessment: { midTerm: 20, codingProject: 40, finalExam: 40 },
      survivalTip: "Danh sách liên kết đơn/đôi, Cây nhị phân tìm kiếm (BST), Cây AVL, Thuật toán Dijkstra/DFS/BFS.",
    },
    {
      code: "DBMS330203",
      name: "Hệ quản trị Cơ sở Dữ liệu (DBMS)",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["PROG130103"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 3.7,
      assessment: { midTerm: 30, labProject: 30, finalExam: 40 },
      survivalTip: "Chuẩn hóa quan hệ 1NF, 2NF, 3NF, BCNF và tối ưu hóa câu truy vấn SQL JOIN/INDEX.",
    },
    {
      code: "OSYS230103",
      name: "Hệ điều hành (Operating Systems)",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["PROG130103"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 4.1,
      assessment: { midTerm: 30, labAssignment: 30, finalExam: 40 },
      survivalTip: "Tiến trình (Process), Luồng (Thread), Đồng bộ hóa (Semaphore/Mutex), Deadlock và Quản lý bộ nhớ ảo.",
    },
    {
      code: "NWKS330103",
      name: "Mạng máy tính (Computer Networks)",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["PROG130103"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 3.9,
      assessment: { midTerm: 30, labProject: 30, finalExam: 40 },
      survivalTip: "Mô hình OSI / TCP/IP, Định tuyến IP Subnetting, Socket TCP/UDP, DNS, HTTP, HTTPS.",
    },
    // Advanced & Specialized Software Engineering
    {
      code: "SWEN330103",
      name: "Nhập môn Kỹ thuật Phần mềm",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["OOPL230103", "DBMS330203"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 3.8,
      assessment: { midTerm: 20, termProject: 50, finalExam: 30 },
      survivalTip: "Mô hình Agile/Scrum, Thiết kế UML (Use Case, Class, Sequence), Quản lý yêu cầu phần mềm.",
    },
    {
      code: "WDEV330203",
      name: "Phát triển Ứng dụng Web",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["SWEN330103", "DBMS330203"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 4.0,
      assessment: { midTerm: 20, webProject: 50, finalExam: 30 },
      survivalTip: "RESTful API, React/Next.js frontend, Node.js/Java Spring backend, Authentication JWT.",
    },
    {
      code: "MOBL330303",
      name: "Lập trình Thiết bị Di động",
      credits: 3,
      theoryCredits: 2,
      labCredits: 1,
      facultyId: "fit",
      prerequisites: ["OOPL230103"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 4.1,
      assessment: { midTerm: 20, appProject: 50, finalExam: 30 },
      survivalTip: "Flutter / React Native, Vòng đời Activity/Component, State Management, SQLite/Firebase.",
    },
    {
      code: "INTR430103",
      name: "Thực tập Doanh nghiệp (Internship)",
      credits: 3,
      theoryCredits: 0,
      labCredits: 3,
      facultyId: "fit",
      prerequisites: ["SWEN330103"],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 3.5,
      assessment: { companyEval: 50, finalReport: 50 },
      survivalTip: "Tối thiểu 10 tuần thực tập tại doanh nghiệp đối tác, có xác nhận đóng dấu của công ty.",
    },
    {
      code: "GRAP440103",
      name: "Khóa luận Tốt nghiệp (Graduation Thesis)",
      credits: 10,
      theoryCredits: 0,
      labCredits: 10,
      facultyId: "fit",
      prerequisites: ["SWEN330103", "INTR430103"],
      coRequisites: [],
      semesterAvailability: [1, 2],
      difficultyRating: 4.8,
      assessment: { supervisorEval: 30, reviewerEval: 20, defenseCouncil: 50 },
      survivalTip: "Yêu cầu tích lũy >= 110 tín chỉ và GPA >= 2.50. Bảo vệ trước Hội đồng chấm khóa luận cấp Khoa.",
    },
    // Political / General Education
    {
      code: "LLCT120105",
      name: "Triết học Mác - Lênin",
      credits: 3,
      theoryCredits: 3,
      labCredits: 0,
      facultyId: "cla",
      prerequisites: [],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 3.2,
      assessment: { midTerm: 40, finalExam: 60 },
      survivalTip: "Cặp phạm trù Nguyên nhân - Kết quả, Quy luật mâu thuẫn và liên hệ thực tiễn kinh tế số Việt Nam.",
    },
    {
      code: "LLCT120205",
      name: "Kinh tế Chính trị Mác - Lênin",
      credits: 2,
      theoryCredits: 2,
      labCredits: 0,
      facultyId: "cla",
      prerequisites: ["LLCT120105"],
      coRequisites: [],
      semesterAvailability: [1, 2, 3],
      difficultyRating: 3.3,
      assessment: { midTerm: 40, finalExam: 60 },
      survivalTip: "Hàng hóa, Giá trị thặng dư, Tích lũy tư bản và Kinh tế thị trường định hướng XHCN.",
    },
  ],

  // Academic Regulations & Scoring Scale (Quy chế tín chỉ đào tạo)
  regulations: {
    gpaScale: "4.0",
    totalCreditsRequiredForGraduation: 150,
    semesterCreditLimits: {
      minimumNormal: 12,
      maximumNormal: 24,
      maximumOverload: 28, // Only for students with previous GPA >= 3.2
      minimumProbation: 10,
    },
    classification: {
      excellent: { min: 3.6, max: 4.0, label: "Xuất sắc" },
      veryGood: { min: 3.2, max: 3.59, label: "Giỏi" },
      good: { min: 2.5, max: 3.19, label: "Khá" },
      average: { min: 2.0, max: 2.49, label: "Trung bình" },
      warning: { min: 0.0, max: 1.99, label: "Cảnh báo học vụ" },
    },
    warningConditions: [
      { id: "WARN_SEM_1", rule: "Điểm trung bình học kỳ < 1.00 ở học kỳ đầu tiên của khóa học" },
      { id: "WARN_SEM_N", rule: "Điểm trung bình học kỳ < 1.20 ở các học kỳ tiếp theo" },
      { id: "WARN_CUM_2", rule: "Điểm trung bình tích lũy < 1.40 sau 2 học kỳ tích lũy" },
      { id: "WARN_CUM_3", rule: "Điểm trung bình tích lũy < 1.60 sau 3 học kỳ tích lũy" },
      { id: "WARN_CUM_4", rule: "Điểm trung bình tích lũy < 1.80 sau 4 học kỳ trở đi" },
      { id: "WARN_DEBT", rule: "Tổng số tín chỉ bị nợ (điểm F chưa trả) vượt quá 24 tín chỉ" },
    ],
    forcedDropCondition: "Bị cảnh báo học vụ 3 lần liên tiếp hoặc vượt quá thời gian tối đa đào tạo (8 năm cho CT 4 năm).",
    retakePolicy: {
      gradeF: "Bắt buộc học lại để tích lũy tín chỉ",
      gradeD: "Được phép đăng ký học lại để cải thiện điểm tích lũy (lấy điểm cao nhất)",
      tuitionRate: "Học lại nộp học phí theo số tín chỉ thực tế của học phần.",
    },
    thesisEligibility: {
      minEarnedCredits: 110,
      minCumulativeGpa: 2.50,
      requiredPrerequisites: ["SWEN330103", "INTR430103"],
    },
    graduationRequirements: [
      "Tích lũy đủ tối thiểu 150 tín chỉ theo đúng chương trình đào tạo của khóa",
      "Điểm trung bình tích lũy toàn khóa đạt từ 2.00 trở lên",
      "Đạt chuẩn đầu ra Ngoại ngữ (TOEIC >= 500 hoặc tương đương B1)",
      "Có chứng chỉ Giáo dục Thể chất và Giáo dục Quốc phòng - An ninh",
      "Không đang trong thời gian bị kỷ luật từ mức đình chỉ học tập trở lên",
    ],
  },
};
