// lib/avatars.js
//
// Bộ sưu tập avatar vector cao cấp phong cách Modern Space & Tech cho
// Sinh viên và Chuyên gia uy tín của StudentHub AI.

export const AVATAR_LIST = [
  // --- AVATAR SINH VIÊN / NGƯỜI DÙNG ---
  {
    id: "student-tech",
    name: "Tech Prodigy",
    role: "student",
    title: "Sinh viên Công nghệ",
    bgGradient: "from-indigo-600 to-purple-600",
    borderGlow: "rgba(99, 102, 241, 0.5)",
    badge: "Verified Student",
    badgeColor: "bg-indigo-500/20 text-indigo-300 border-indigo-500/40",
    iconType: "code",
    emoji: "💻",
    description: "Đam mê lập trình, AI và phát triển phần mềm",
  },
  {
    id: "student-ai",
    name: "Cyber AI Student",
    role: "student",
    title: "Nghiên cứu Trí tuệ nhân tạo",
    bgGradient: "from-cyan-600 to-blue-600",
    borderGlow: "rgba(6, 182, 212, 0.5)",
    badge: "AI Explorer",
    badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/40",
    iconType: "sparkles",
    emoji: "🤖",
    description: "Tìm tòi Deep Learning, Prompt Engineering & LLM",
  },
  {
    id: "student-scholar",
    name: "Diligent Scholar",
    role: "student",
    title: "Học giả Năng nổ",
    bgGradient: "from-emerald-600 to-teal-600",
    borderGlow: "rgba(16, 185, 129, 0.5)",
    badge: "Top Learner",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
    iconType: "book",
    emoji: "📚",
    description: "Chăm chỉ nghiên cứu học thuật và tài liệu",
  },
  {
    id: "student-designer",
    name: "Creative Creator",
    role: "student",
    title: "Nhà Thiết kế Sáng tạo",
    bgGradient: "from-rose-600 to-pink-600",
    borderGlow: "rgba(244, 63, 94, 0.5)",
    badge: "Design Master",
    badgeColor: "bg-rose-500/20 text-rose-300 border-rose-500/40",
    iconType: "palette",
    emoji: "🎨",
    description: "Đam mê UI/UX, đồ họa và trải nghiệm người dùng",
  },
  {
    id: "student-leader",
    name: "Student Leader",
    role: "student",
    title: "Thủ lĩnh Sinh viên",
    bgGradient: "from-amber-600 to-orange-600",
    borderGlow: "rgba(245, 158, 11, 0.5)",
    badge: "Community Star",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
    iconType: "star",
    emoji: "🚀",
    description: "Nhiệt huyết kết nối cộng đồng học tập",
  },
  {
    id: "student-explorer",
    name: "Future Innovator",
    role: "student",
    title: "Nhà Đổi mới Tương lai",
    bgGradient: "from-violet-600 to-indigo-700",
    borderGlow: "rgba(139, 92, 246, 0.5)",
    badge: "Innovator",
    badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/40",
    iconType: "rocket",
    emoji: "💡",
    description: "Yêu thích giải quyết vấn đề thực tế",
  },

  // --- AVATAR CHUYÊN GIA UY TÍN ---
  {
    id: "expert-ai",
    name: "Dr. AI Scientist",
    role: "expert",
    title: "Chuyên gia AI & Machine Learning",
    bgGradient: "from-amber-500 via-orange-500 to-yellow-500",
    borderGlow: "rgba(245, 158, 11, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "award",
    emoji: "🧠",
    description: "5+ năm nghiên cứu AI, LLM & Khoa học Dữ liệu",
  },
  {
    id: "expert-architect",
    name: "Master Architect",
    role: "expert",
    title: "Kiến trúc sư Hệ thống Phần mềm",
    bgGradient: "from-blue-600 via-indigo-600 to-purple-600",
    borderGlow: "rgba(59, 130, 246, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "cpu",
    emoji: "🏛️",
    description: "Chuyên gia Cloud, Microservices & High-load backend",
  },
  {
    id: "expert-professor",
    name: "Distinguished Professor",
    role: "expert",
    title: "Giảng viên Đại học / Cố vấn",
    bgGradient: "from-purple-600 via-violet-600 to-amber-600",
    borderGlow: "rgba(168, 85, 247, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "mortarboard",
    emoji: "🎓",
    description: "Giảng dạy đại học, định hướng nghiên cứu khoa học",
  },
  {
    id: "expert-techlead",
    name: "Senior Tech Lead",
    role: "expert",
    title: "Kỹ sư Trưởng / Tech Lead",
    bgGradient: "from-emerald-600 via-teal-600 to-cyan-600",
    borderGlow: "rgba(16, 185, 129, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "shield",
    emoji: "⚡",
    description: "Dẫn dắt dự án lớn, cố vấn kỹ thuật và tuyển dụng IT",
  },
  {
    id: "expert-mentor",
    name: "Executive Mentor",
    role: "expert",
    title: "Cố vấn Khởi nghiệp & Hướng nghiệp",
    bgGradient: "from-rose-600 via-orange-600 to-amber-600",
    borderGlow: "rgba(244, 63, 94, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "trending-up",
    emoji: "💼",
    description: "Tư vấn CV, phỏng vấn, định hướng nghề nghiệp sinh viên",
  },
  {
    id: "expert-security",
    name: "Cyber Security Guru",
    role: "expert",
    title: "Chuyên gia An ninh Mạng",
    bgGradient: "from-red-600 via-purple-700 to-indigo-800",
    borderGlow: "rgba(239, 68, 68, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "shield-alert",
    emoji: "🛡️",
    description: "Bảo mật hệ thống, DevSecOps & Kiểm thử thâm nhập",
  },
];

export const VIETNAM_UNIVERSITIES = [
  "Đại học Bách Khoa Hà Nội (HUST)",
  "Đại học Quốc gia Hà Nội (VNU)",
  "Đại học Quốc gia TP.HCM (VNU-HCM)",
  "Đại học Bách Khoa TP.HCM (HCMUT)",
  "Đại học Công nghệ thông tin (UIT)",
  "Đại học Khoa học Tự nhiên (HCMUS / HUS)",
  "Đại học Kinh tế Quốc dân (NEU)",
  "Đại học Ngoại Thương (FTU)",
  "Học viện Công nghệ Bưu chính Viễn thông (PTIT)",
  "Đại học FPT (FPT University)",
  "Đại học RMIT Việt Nam",
  "Đại học Sư phạm Kỹ thuật TP.HCM (HCMUTE)",
  "Đại học Tôn Đức Thắng (TDTU)",
  "Đại học Cần Thơ (CTU)",
  "Đại học Đà Nẵng (UD)",
];

export const EXPERT_FIELDS = [
  "Trí tuệ nhân tạo (AI & Machine Learning)",
  "Kỹ thuật phần mềm (Web / Mobile / Cloud)",
  "Khoa học Dữ liệu (Data Science & Analytics)",
  "An ninh mạng & Bảo mật (Cyber Security)",
  "Thiết kế UI/UX & Sản phẩm (Product Design)",
  "Kinh tế, Tài chính & Khởi nghiệp (Fintech & Startup)",
  "Ngoại ngữ & Luyện thi chứng chỉ (IELTS/TOEIC)",
  "Kỹ năng mềm & Định hướng nghề nghiệp",
];

export function getAvatarById(id) {
  if (!id) return AVATAR_LIST[0];
  const found = AVATAR_LIST.find((a) => a.id === id);
  return found || AVATAR_LIST[0];
}

export function getDefaultAvatar(role = "student") {
  return role === "expert" ? AVATAR_LIST[6] : AVATAR_LIST[0];
}
