// lib/avatars.js
//
// Bộ sưu tập avatar vector cao cấp phong cách Modern Space & Tech cho
// Sinh viên và Chuyên gia uy tín của StudentHub AI.

export const AVATAR_LIST = [
  // --- AVATAR SINH VIÊN / NGƯỜI DÙNG ---
  {
    id: "student-tech",
    name: "Tech Prodigy",
    role: "student",
    title: "Sinh viên Công nghệ",
    bgGradient: "from-teal-600 to-emerald-600",
    borderGlow: "rgba(52, 231, 196, 0.5)",
    badge: "Verified Student",
    badgeColor: "bg-teal-500/20 text-teal-300 border-teal-500/40",
    iconType: "code",
    emoji: "💻",
    description: "Đam mê công nghệ, bảo mật và an toàn không gian mạng",
  },
  {
    id: "student-ai",
    name: "Cyber Guardian",
    role: "student",
    title: "Hiệp sĩ An toàn Mạng",
    bgGradient: "from-cyan-600 to-blue-600",
    borderGlow: "rgba(6, 182, 212, 0.5)",
    badge: "Anti-Scam Scout",
    badgeColor: "bg-cyan-500/20 text-cyan-300 border-cyan-500/40",
    iconType: "shield",
    emoji: "🛡️",
    description: "Tích cực phát hiện và cảnh báo các bẫy lừa đảo sinh viên",
  },
  {
    id: "student-scholar",
    name: "Diligent Scholar",
    role: "student",
    title: "Học giả Năng nổ",
    bgGradient: "from-emerald-600 to-teal-600",
    borderGlow: "rgba(16, 185, 129, 0.5)",
    badge: "Top Learner",
    badgeColor: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
    iconType: "book",
    emoji: "📚",
    description: "Chăm chỉ nghiên cứu và chia sẻ kinh nghiệm học tập thực tế",
  },
  {
    id: "student-designer",
    name: "Creative Creator",
    role: "student",
    title: "Nhà Thiết kế Sáng tạo",
    bgGradient: "from-rose-600 to-pink-600",
    borderGlow: "rgba(244, 63, 94, 0.5)",
    badge: "Design Master",
    badgeColor: "bg-rose-500/20 text-rose-300 border-rose-500/40",
    iconType: "palette",
    emoji: "🎨",
    description: "Đam mê UI/UX, đồ họa và truyền thông số",
  },
  {
    id: "student-leader",
    name: "Community Star",
    role: "student",
    title: "Thủ lĩnh Sinh viên",
    bgGradient: "from-amber-600 to-orange-600",
    borderGlow: "rgba(245, 158, 11, 0.5)",
    badge: "Community Star",
    badgeColor: "bg-amber-500/20 text-amber-300 border-amber-500/40",
    iconType: "star",
    emoji: "🚀",
    description: "Nhiệt huyết kết nối và bảo vệ cộng đồng sinh viên",
  },
  {
    id: "student-explorer",
    name: "Future Innovator",
    role: "student",
    title: "Nhà Đổi mới Tương lai",
    bgGradient: "from-violet-600 to-indigo-700",
    borderGlow: "rgba(139, 92, 246, 0.5)",
    badge: "Innovator",
    badgeColor: "bg-violet-500/20 text-violet-300 border-violet-500/40",
    iconType: "rocket",
    emoji: "💡",
    description: "Yêu thích giải quyết vấn đề thực tế",
  },

  // --- AVATAR CHUYÊN GIA UY TÍN ---
  {
    id: "expert-security",
    name: "Cyber Security Guru",
    role: "expert",
    title: "Chuyên gia An ninh Mạng & Phòng chống Lừa đảo",
    bgGradient: "from-teal-500 via-emerald-600 to-cyan-700",
    borderGlow: "rgba(52, 231, 196, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "shield-alert",
    emoji: "🛡️",
    description: "Chuyên sâu nhận diện lừa đảo, điều tra số và an ninh mạng",
  },
  {
    id: "expert-legal",
    name: "Legal Counsel",
    role: "expert",
    title: "Cố vấn Pháp lý & Quyền lợi Sinh viên",
    bgGradient: "from-amber-500 via-orange-500 to-yellow-600",
    borderGlow: "rgba(245, 158, 11, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "award",
    emoji: "⚖️",
    description: "Tư vấn hợp đồng trọ, pháp lý việc làm và phòng chống chiếm đoạt tài sản",
  },
  {
    id: "expert-ai",
    name: "Dr. AI Scientist",
    role: "expert",
    title: "Chuyên gia AI & Deep Learning",
    bgGradient: "from-indigo-600 via-purple-600 to-pink-600",
    borderGlow: "rgba(99, 102, 241, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "cpu",
    emoji: "🧠",
    description: "Nghiên cứu mô hình nhận diện deepfake và xử lý ngôn ngữ tự nhiên",
  },
  {
    id: "expert-finance",
    name: "Fintech & Banking Analyst",
    role: "expert",
    title: "Chuyên gia Tài chính & Ngân hàng",
    bgGradient: "from-emerald-600 via-teal-600 to-cyan-600",
    borderGlow: "rgba(16, 185, 129, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "trending-up",
    emoji: "💳",
    description: "Cảnh báo bẫy tín dụng đen, lừa đảo chuyển khoản & đa cấp trực tuyến",
  },
  {
    id: "expert-housing",
    name: "Student Housing Advisor",
    role: "expert",
    title: "Cố vấn Nhà trọ & Bất động sản Sinh viên",
    bgGradient: "from-blue-600 via-indigo-600 to-purple-600",
    borderGlow: "rgba(59, 130, 246, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "building",
    emoji: "🏠",
    description: "Xác thực danh sách trọ an toàn, chống cọc ảo và ép giá sinh viên",
  },
  {
    id: "expert-professor",
    name: "Distinguished Professor",
    role: "expert",
    title: "Giảng viên Đại học / Cố vấn Học bổng",
    bgGradient: "from-purple-600 via-violet-600 to-amber-600",
    borderGlow: "rgba(168, 85, 247, 0.7)",
    badge: "⭐ Chuyên Gia Uy Tín",
    badgeColor: "bg-amber-500/25 text-amber-200 border-amber-400/60 shadow-[0_0_15px_rgba(245,158,11,0.3)]",
    iconType: "mortarboard",
    emoji: "🎓",
    description: "Xác minh thông tin học bổng chính thống, tránh bẫy đóng phí xét tuyển giả",
  },
];

export const VIETNAM_UNIVERSITIES = [
  "Đại học Bách Khoa Hà Nội (HUST)",
  "Đại học Quốc gia Hà Nội (VNU)",
  "Đại học Quốc gia TP.HCM (VNU-HCM)",
  "Đại học Bách Khoa TP.HCM (HCMUT)",
  "Đại học Công nghệ thông tin (UIT)",
  "Đại học Khoa học Tự nhiên (HCMUS / HUS)",
  "Đại học Kinh tế Quốc dân (NEU)",
  "Đại học Ngoại Thương (FTU)",
  "Học viện Công nghệ Bưu chính Viễn thông (PTIT)",
  "Đại học FPT (FPT University)",
  "Đại học RMIT Việt Nam",
  "Đại học Sư phạm Kỹ thuật TP.HCM (HCMUTE)",
  "Đại học Tôn Đức Thắng (TDTU)",
  "Đại học Cần Thơ (CTU)",
  "Đại học Đà Nẵng (UD)",
];

export const EXPERT_FIELDS = [
  "An ninh mạng & Phòng chống lừa đảo (Cyber Security & Anti-Fraud)",
  "Luật & Tư vấn Pháp lý (Legal & Rights)",
  "Tài chính, Ngân hàng & Fintech (Finance)",
  "Bất động sản & Nhà trọ Sinh viên (Housing)",
  "Lập trình & Kỹ thuật Phần mềm (Software & Web)",
  "Trí tuệ nhân tạo & Khoa học Dữ liệu (AI & Data)",
  "Y Dược & Sức khỏe Cộng đồng (Healthcare)",
  "Học bổng & Hướng nghiệp Sinh viên (Scholarships)",
];

export function getAvatarById(id) {
  if (!id) return AVATAR_LIST[0];
  const found = AVATAR_LIST.find((a) => a.id === id);
  return found || AVATAR_LIST[0];
}

export function getDefaultAvatar(role = "student") {
  return role === "expert" ? AVATAR_LIST[6] : AVATAR_LIST[0];
}
